# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7416bbcce5ea4c62ebb78d73b09e6c31babc831f945d26103e7e7f2a7e060af7d62156e8664f7b41f39fae7fbc24a705c2fa655d54a58531ab4d9c5fe4162f9

test:
  secret_key_base: a50f967db04189de40c0f09f9fbbe5b38381e5bebab894588cec4280dcbbb7c75d8effc693ae72a74a0a3512d5dd64f2a3d13481c5b2585b289f150d48152d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
